In [1]:
import pandas as pd

In [19]:
ratings = pd.read_csv(r"data/ml-100k/u.data", sep="\t", names=["user_id", "movie_id", "rating", "timestamp"])

In [20]:
ratings.head()

   user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [21]:
ratings.shape

(100000, 4)

In [24]:
ratings["label"] = (ratings["rating"] >= 4).astype(int)

In [25]:
ratings[["rating", "label"]].head(10)

   rating  label
0       3      0
1       3      0
2       1      0
3       2      0
4       1      0
5       4      1
6       2      0
7       5      1
8       3      0
9       3      0

In [26]:
ratings["label"].value_counts()

label
1    55375
0    44625
Name: count, dtype: int64

In [29]:
ratings["rating"].value_counts().sort_index()

rating
1     6110
2    11370
3    27145
4    34174
5    21201
Name: count, dtype: int64

In [33]:
movies = pd.read_csv(r"data/ml-100k/u.item",    sep="|",
    encoding="latin-1",
    header=None
)

In [34]:
movies.shape

(1682, 24)

In [35]:
movies.head()

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0